GeradorProtocoloAtendimento.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GeradorProtocoloAtendimento.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GeradorProtocoloAtendimento.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GeradorProtocoloAtendimento.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly HttpClient _httpClient;
        private readonly string _url;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
            _url = "https://localhost:44397/api";
        }

        public string Protocolo { get; set; }
        public void OnGet()
        {

        }

        public void OnPostSubmit(string idEmpresa, DateTime data)
        {
            try
            {
                var response = _httpClient.GetAsync($"{_url}/Gerar?empresaId={idEmpresa}&data={data}").GetAwaiter().GetResult();
                if (response.IsSuccessStatusCode)
                {
                    this.Protocolo = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                }
                else
                {
                    this.Protocolo = "Erro ao gerar protocolo(API)";
                }
            }
            catch (Exception ex)
            {
                this.Protocolo = "Erro ao gerar protocolo" + ex.Message;
            }
        }
    }
}

GeradorProtocoloAtendimento.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GeradorProtocoloAtendimento.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GeradorProtocoloAtendimento.Web/Pages/Index.cshtml
@page
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerador de Protocolo</title>
    <link href="~/css/StyleSheet.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <form id="form" method="post">
        <div class="container">
            <div class="header">
                <h2>Gerador de Protocolo</h2>
            </div>
            <div class="content">
                <div class="form-group">
                    <label for="nome">Id empresa:</label>
                    <input type="text" name="idEmpresa" id="idEmpresa" placeholder="Digite o id da empresa">
                </div>
                <div class="form-group">
                    <label for="data">Data:</label>
                    <input type="date" name="data" id="data">
                </div>
                <button type="submit" asp-page-handler="Submit" >Gerar Protocolo</button>
            </div>
        </div>
    </form>
    <br/>
    <div>
        <label for="nome">Protocolo:</label>
        <input type="text" value="@Model.Protocolo" readonly>
    </div>

</body>
</html>

GeradorProtocoloAtendimento.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeradorProtocoloAtendimento.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeradorProtocoloAtendimento.Web.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GeradorProtocoloAtendimento.Web 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>